name: Docker build

on:
  pull_request:
    branches:
      - "**"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t test-image:pr-$GITHUB_SHA .

      - name: Cleanup Docker image
        run: docker rmi test-image:pr-$GITHUB_SHA
